### ISSUE TITLE
It is not working when access relation model by using binary(16) UUID

### ISSUE THREAD

**Issue by DesmondPang** [alsofronie/eloquent-uuid#3] opened 2016-01-10 19:31 UTC
It always return null for relation. For example. $user = User::with('posts')->find( $user_hex_uuid ); It return empty for posts relation.

**Comment by alsofronie** [comment] 2016-01-10 20:18
I've added relationships (one to many) just to test the relationship. The `phpunit` is still green. 
I' will close this issue. If you're having difficulties, please better describe what you are trying to do and I'll look into it.

**Comment by DesmondPang** [comment] 2016-01-11 08:00
I found that the problem is in eager loading.  From the following test, you can see when I use eager load function, with() and load(), it will return empty result. However, from the query log you can see the query is the same one. I don't know why. I have already spent one day on this issue. =.= 

```
public function index($id)
{

    DB::enableQueryLog();

    $project = Project::find($id);
   // $project = Project::with('author')->find($id);
    echo $project->load('author');
    echo $project->author;
    echo "<br><br>";

    print_r(DB::getQueryLog());


    echo "<br><br>";
    $project = Project::find($id);
    echo "<br><br>";
    echo $project;
    echo "<br><br>";
    echo $project->author;
    echo "<br><br>";

    print_r(DB::getQueryLog());

}
```

//Output on browser
{"id":548,"name":"Project A","deleted_at":null,"created_at":"-0001-11-30 00:00:00","updated_at":"-0001-11-30 00:00:00","user_id":"3b64f2a6-b7be-11","author":null}

Array ( [0] => Array ( [query] => select \* from `projects` where `id` = ? limit 1 [bindings] => Array ( [0] => 548bfb12-b7be-11 ) [time] => 0.45 ) [1] => Array ( [query] => select \* from `users` where `users`.`id` in (?) [bindings] => Array ( [0] => 3b64f2a6-b7be-11 ) [time] => 0.45 ) ) 

{"id":548,"name":"Project A","deleted_at":null,"created_at":"-0001-11-30 00:00:00","updated_at":"-0001-11-30 00:00:00","user_id":"3b64f2a6-b7be-11"}

{"id":3,"name":"AA","email":"AA","created_at":"2016-01-11 13:41:31","updated_at":"-0001-11-30 00:00:00"}

Array ( [0] => Array ( [query] => select \* from `projects` where `id` = ? limit 1 [bindings] => Array ( [0] => 548bfb12-b7be-11 ) [time] => 0.45 ) [1] => Array ( [query] => select \* from `users` where `users`.`id` in (?) [bindings] => Array ( [0] => 3b64f2a6-b7be-11 ) [time] => 0.45 ) [2] => Array ( [query] => select \* from `projects` where `id` = ? limit 1 [bindings] => Array ( [0] => 548bfb12-b7be-11 ) [time] => 0.48 ) [3] => Array ( [query] => select \* from `users` where `users`.`id` = ? limit 1 [bindings] => Array ( [0] => 3b64f2a6-b7be-11 ) [time] => 0.41 ) )

**Comment by alsofronie** [comment] 2016-01-11 19:49
One thing comes to mind: you use a char id and I assume you are using binary uuid. You can use the setters and getters, but I do not think they will function in the same way with early binding.

Try and use the binary id with your queries.

**Comment by DesmondPang** [comment] 2016-01-12 07:14
No, they are in binary(16). Because I did not use bin2hex to convert the binary uuid into hex form so you see all the id are not are uuid format.

**Comment by DesmondPang** [comment] 2016-01-12 07:25
I add this into Project model

```
public function setIdAttribute($value)
{

    $this->attributes['id'] = hex2bin($value);
}

public function getIdAttribute($value)
{
    return bin2hex($value);
}

public function setUserIdAttribute($value)
{

    $this->attributes['user_id'] = hex2bin($value);
}

public function getUserIdAttribute($value)
{
    return bin2hex($value);
}
```

And add this into User model

```
public function setIdAttribute($value)
{

    $this->attributes['id'] = hex2bin($value);
}

public function getIdAttribute($value)
{
    return bin2hex($value);
}
```

Result

{"id":"35343862666231322d623762652d3131","name":"Project A","deleted_at":null,"created_at":"-0001-11-30 00:00:00","updated_at":"-0001-11-30 00:00:00","user_id":"33623634663261362d623762652d3131","author":null}

Array ( [0] => Array ( [query] => select \* from `projects` where `id` = ? limit 1 [bindings] => Array ( [0] => 548bfb12-b7be-11 ) [time] => 0.5 ) [1] => Array ( [query] => select \* from `users` where `users`.`id` in (?) [bindings] => Array ( [0] => 33623634663261362d623762652d3131 ) [time] => 0.43 ) ) 

{"id":"35343862666231322d623762652d3131","name":"Project A","deleted_at":null,"created_at":"-0001-11-30 00:00:00","updated_at":"-0001-11-30 00:00:00","user_id":"33623634663261362d623762652d3131"}

Array ( [0] => Array ( [query] => select \* from `projects` where `id` = ? limit 1 [bindings] => Array ( [0] => 548bfb12-b7be-11 ) [time] => 0.5 ) [1] => Array ( [query] => select \* from `users` where `users`.`id` in (?) [bindings] => Array ( [0] => 33623634663261362d623762652d3131 ) [time] => 0.43 ) [2] => Array ( [query] => select \* from `projects` where `id` = ? limit 1 [bindings] => Array ( [0] => 548bfb12-b7be-11 ) [time] => 0.47 ) [3] => Array ( [query] => select \* from `users` where `users`.`id` = ? limit 1 [bindings] => Array ( [0] => 33623634663261362d623762652d3131 ) [time] => 0.38 ) )

As you can see, it convert the binary(16) uuid into hex, but still cannot get result in eager loading

**Comment by alsofronie** [comment] 2016-01-13 21:31
I will study this, but I'm assuming the `find` method is not using the `setIdAttribute` method.

**Edit** it turns out the model **is using** in some cases the `getIdAttribute` and that's why you got in your queries the hex version on your bindings (which will not work). The only way (for now) is to use another attribute (for example `hex_id` with `getHexIdAttribute` and `setHextIdAttribute` but you must not _overload_ the setters and getters for `id`. It has to remain always in the `bin` form.

My last commit is showing both saving and loading (including eager) and it's working (phpunit).

**Comment by DesmondPang** [comment] 2016-01-18 11:06
Thank you so much. I have already changed using auto-increment with binary 16 uuid. The primary keys and foreign keys keep use bigInt instead of binary 16 uuid. However, I will test it later and maybe I will use in it in my next project. Thank you for you answers again because not so people realise this issue and they only told me use other solutions.

**Comment by DesmondPang** [comment] 2016-03-16 08:48
Hi, I tried to test it again recently. I tested your unit test. It works. However, when I move to the real database, it doesn't work. I even copy your classes to test.

Finally, I found the issue that is about database. I changed the connection to mysql in your unit test class. It did not work. I have tried InnoDB and MyISAM. They both didn't work.

In you unit test, the default connection is SQLite. Please change the following code with MySQL connection.

```
public function connection($name = null)
{
    if (isset($this->connection)) {
        return $this->connection;
    }
    return $this->connection = new Illuminate\Database\MySqlConnection(new PDO('mysql:host=127.0.0.1;dbname=yourDBName','username','password!'));
}
```

Result:

{"username":"first-user","password":"secret","id":"4a7b83282d2942e78058af80b7b660d1","updated_at":"2016-03-16 08:33:31","created_at":"2016-03-16 08:33:31","posts":[]}.

See the result for relation posts is always empty. 

Do you know how to fix it or need some configurations in MySql? Thank you for your help. I have spent so much time at this issue. =.=

**Comment by alsofronie** [comment] 2016-03-16 10:00
Hi. The PDO abstraction layer is exactly about that, so you do not care about the grunt implementation of the database system. I will look into it right away.

**Comment by DesmondPang** [comment] 2016-03-16 11:23
The above result was shown in unit test because I added the echo $firstUser->load('posts'); in the testRelationshipWithBinUuid() function.  

Also I removed tearDown() code. The created records during testing would saved in my MySQL database. I found that the user_id in post table are different from the ids in users table. That's why the it shows the empty posts[] when you called relationship queries. Even I changed the user_id manually that match the exactly id in users table, it still show empty result.

**Comment by alsofronie** [comment] 2016-03-16 16:36
What you need to do is **NOT** to touch setIdAttribute and getIdAttribute. You must have to let them as they are, because, unfortunately, some of the intrinsic Laravel Eloquent Model use `$this->attributes['id']` which will bring the binary version, and others use `$this->getAttribute('id')` which will call the getIdAttribute function i think.

Everything else works as expected. Here is what I've been working on on real app (striped down):

Schema for articles, the `up` function

```
        Schema::create('articles', function (Blueprint $table) {
            $table->string('title');
            $table->timestamps();
        });
        DB::statement('ALTER TABLE `articles` ADD `id` BINARY(16)');
        DB::statement('ALTER TABLE `articles` ADD PRIMARY KEY(`id`)');
```

Schema for comments, the `up()` function

```
        Schema::create('comments', function (Blueprint $table) {
            $table->string('name');
            $table->timestamps();
        });
        DB::statement('ALTER TABLE `comments` ADD `id` BINARY(16);');
        DB::statement('ALTER TABLE `comments` ADD `article_id` BINARY(16)');
        DB::statement(' ALTER TABLE `comments` ADD PRIMARY KEY(`id`)');
```

The `Article.php` model:

```
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Alsofronie\Uuid\UuidBinaryModelTrait;

class Article extends Model
{
    use UuidBinaryModelTrait;

    protected $hidden = ['id'];
    protected $appends = ['id_string'];

    public function comments()
    {
        return $this->hasMany('App\Comment');
    }

}
```

The `Comment.php` model:

```
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Alsofronie\Uuid\UuidBinaryModelTrait;

class Comment extends Model
{
    use UuidBinaryModelTrait;
    protected $hidden = ['id', 'article_id'];
    protected $appends = ['id_string', 'article_id_string'];

    public function article()
    {
        return $this->belongsTo('App\Article');
    }

    public function getArticleIdStringAttribute()
    {
        return bin2hex($this->getAttribute('article_id'));
    }
}
```

And a test, using MySQL:

```
        $article = new App\Article();
        $article->title = 'Article 1';
        $article->save();

        $comment1 = new App\Comment();
        $comment1->article_id = $article->id;
        $comment1->name = 'Comment 1';
        $comment1->save();

        $comment2 = new App\Comment();
        $comment2->article_id = $article->id;
        $comment2->name = 'Comment 2';
        $comment2->save();

        $receivedArticle = App\Article::with('comments')->find($article->id);

        dd($receivedArticle->toArray());
```

Yields as expected.

**Comment by alsofronie** [comment] 2016-03-16 16:37
It seems the problem is that the static function `find` defined on the trait is not called when you run `find` on the model.

As expected, even if the intrinsic `id` value is kept binary and the displayed value is hex, when you are using `find` or `where`, it's not on the model but on the query builder. One workaround is to use `Model::find(hex2bin($id));` but I do not think there is a possible solution using only traits.

**Comment by DesmondPang** [comment] 2016-03-17 07:07
Thank you so much your help. 

Now, using xxx_id_string in $appends is a possible solution but not perfect.

I am wondering if it is possible to override Laravel internal query functions that add UNHEX()  and HEX() functions to final queries to process uuids before access the database. Then, we no need to do anything on the model layer.

**Comment by alsofronie** [comment] 2016-03-17 09:39
Unfortunately that's the query builder and one will have to dig into grammars and everything.

This issue will remain open until the documentation will get updated in order to reflect these problems.

**Closed as completed** 2016-08-31 19:42 UTC

**Comment by golinmarq** [comment] 2016-09-29 21:23
I have the same issue but, in my case article has an integer primary key. When I called Article::find($id) I get a null value
