### ISSUE TITLE
Queuing models gives invalid payload

### ISSUE THREAD

**Issue by JValck** [alsofronie/eloquent-uuid#29] opened 2017-06-07 16:37 UTC
Hi,

when working with the binary traits, it is currently impossible to to add them to the queue as the models contain malformed UTF-8. A possible solution is to modify the serialization process (see laravel/framework#19252 and laravel/framework#15065).

I currently created a dirty workaround by creating an extra `trait`. In my case all the binary fields in the database end with `id`, this declares the check in the `unserialize` method:

```
<?php

namespace App;

/**
* Allows serialization and deserialization for models
* //TODO: fix slow deserialization
*/
trait UuidBinaryModelSerialization
{
	public function serialize()
    {
        return json_encode($this->toArray());
    }

    public function unserialize($stringRepresentationOfObject)
    {
        $decodedArray = json_decode($stringRepresentationOfObject);
        foreach ($decodedArray as $key => $value) {
            if(substr($key, -2) === "id"){//convert to binary
                $this->$key = $this->toOptimized($value);
            }else{
                $this->$key = $value;
            }            
        }
    }
```

Another possibility is adding an array to the models containing the names of the fields that are binary. This should decrease the amount of checks in the `for`-loop in `unserialize`.

Would it be possible to allow an OOTB solution for this serialization process?

**Comment by alsofronie** [comment] 2017-06-07 16:52
Hello @JValck,

Can you suggest a small Unit Test that would fail with the trait but would be green otherwise?

The obvious solution would be to encapsulate the binary object in a class that would automatically cast to a string if needed (similar on what Taylor did with `Carbon` for dates) but I fear it would not be resolvable through a trait anymore, because of the relationships involved in Eloquent.

I cannot override the `toJson()`, `toArray()` or any other method from Eloquent Model in the trait, because that will basically deny the functionality to the user. A reflection solution will be slower than anything I can think of right now.

**Comment by JValck** [comment] 2017-06-08 09:38
Actually the `toArray()` is already overridden.
So I wrote a [Unit Test](https://gist.github.com/JValck/1367dbbf01f61ae40c499e72782eb298#file-unittest-php) as you requested.
Currently all the tests pass. So I'm wondering the issue would be related to `Mailables`. As in my case I'm using `Mailables` instead of a `Job`.

**Comment by alsofronie** [comment] 2017-06-08 17:18
Thanks for the unit test.

I think the issue is the userialize procedure in the queue job workers, specifically`fromJson` (in the `HasAttributes` trait in `Model`). 

This issue requires branching for different Laravel versions, as from 5.1 to 5.4 the code changed with every minor version increment. I'm assuming you are using 5.4, which I cannot test right now.

Please add the following function to the original `BinaryUuidTrait`. I am hoping it will resolve this issue.

    public function fromJson($json, $asObject = false)
    {
        $mixed = parent::fromJson($json, $asObject);
        $key = $model->getKeyName();
        if ($asObject) {
            $mixed->{$key} = static::toOptimized($mixed->{$key});
        } else {
            $mixed[$key] = static::toOptimized($mixed[$key]);
        }

        return $mixed;
    }

Hope it helps.

**Comment by alsofronie** [comment] 2017-07-20 14:01
I think this is related to #30. Ill close it for now as all the tests are green.

**Closed as completed by alsofronie** 2017-07-20 14:01 UTC

**Comment by JValck** [comment] 2017-07-21 08:28
The issue isn't fixed, although I think it's out of the scope of this repo.

When a model is queued, Laravel will [serialize the object](https://github.com/laravel/framework/blob/5.4/src/Illuminate/Queue/Queue.php#L118). The serialized object still has the binary representation of the id, causing ```json_encode``` to fail.
For example: if you queue a mail with a model, Laravel will create a ```SendQueuedMailable``` containing a ```Mailable``` with the native object with the binary id.

You can solve this by implementing your own ```serialize```-method.
